### ISSUE TITLE
Draggable Marker not moving

### ISSUE THREAD

**Issue by eduboxgithub** [oscarfonts/mapbox-gl-cordova-offline#32] opened 2018-12-11 17:19 UTC
When a add a marker and set the property "draggable=true" the marker does not move when I'm testing on the device (Android).

```
import * as MapboxGLOffline from 'mapbox-gl-cordova-offline';

let marker = new MapboxGLOffline.Marker( { draggable: true })
                     .setLngLat(new MapboxGLOffline.LngLat(+coords.lng, +coords.lat))
                     .addTo(map);
```

Do I need to do something special?

Is it because the mapbox version?
It it possible to update it to the latest version 0.51?

**Comment by eduboxgithub** [comment] 2018-12-17 16:21
Don't know if this is correct but reading the changelog https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md the ability to drag markers was only introduced in 0.46.0:

https://github.com/mapbox/mapbox-gl-js/pull/6687

How can we update the Mapbox version dependency?

**Comment by oscarfonts** [comment] 2018-12-24 09:11
Have you tried to update the mapbox dependency and build the project?
A PR if succeeded, or any feedback in case of problems will be kindly appreciated. :)

**Comment by eduboxgithub** [comment] 2019-02-05 11:55
I was trying to make a few changes to update to 0.52, but I noticed there's already an PR with that change.

https://github.com/oscarfonts/mapbox-gl-cordova-offline/pull/36#issue-246059134

**Comment by michogar** [comment] 2019-02-05 12:53
Hi @eduboxgithub 

yes, for a project I needed to update the library with a more updated version of Mapbox. Mapbox has changed a method in `ajax.jx` and now it cans load files using window.fetch api when this api is available In our case, Cordova webview has this API and Mapbox tries to use it. But the problem is that this API doesn't allow load files using protocol `file://` which is used to load sprites and glyphs in this library. To avoid this I made a workaround setting the `window.fetch = undefined` but this is a very ugly and heavy hack because maybe another library could use this api and this change could break these other libraries.

I have made a fork of this repo and I have updated the library to use 0.52 mapbox version. You can test it here, the version updated is the v0.2.1

[https://github.com/northings/mapbox-gl-cordova-offline](https://github.com/northings/mapbox-gl-cordova-offline)

The inclusion of the use of `window.fetch`is from mapbox 0.49.version, so, if you couldn't include this ugly hack in your app you shouldn't update to a higher version of Mapbox.

There is a branch updated until mapbox 0.49 version here:

[https://github.com/northings/mapbox-gl-cordova-offline/tree/feature/mapbox.v0.49.0](https://github.com/northings/mapbox-gl-cordova-offline/tree/feature/mapbox.v0.49.0)

I am still thinking which could be the best way to avoid the problem with the use of `window.fetch`, but I haven't found an elegant solution yet.

Cheers!!.

**Comment by eduboxgithub** [comment] 2019-02-11 12:17
@michogar Hello, thank you so much for your feedback.

I was doing some extra testing with the forks you provided, and I notice a new version of mapbox was release (v0.53). I was reading their changlog and I think they fixed the issue regarding the fetch/file:// problem.

https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md

**Allow file:// protocol in XHR requests for Cordova/Ionic/etc (#7818)**

https://github.com/mapbox/mapbox-gl-js/pull/7818

**Comment by michogar** [comment] 2019-02-11 12:26
Cool!!, these are good news. I'll try to test the library with that version of Mapbox ASAP. If you advance in the integration of the latest Mapbox version, please, maybe could you make a PR?.

Thank you very much, and enjoy mapbox-gl-cordova-offline!!

**Comment by michogar** [comment] 2019-03-30 07:42
Hi @eduboxgithub 

I've just updated the library with the latest Mapbox GL JS version, 0.53.1. Please check if problems with markers disappear and we can closing the issue.

Best.

**Closed** 2019-05-02 11:28 UTC
